# only do this if homebrew is installed, aka on macs
if [ -d "/opt/homebrew/bin/brew" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

export PATH="$HOME/.local/bin:$HOME/bin:$PATH"

# rust
. "$HOME/.cargo/env"

export EDITOR="nvim"
