typeset -U path

# only do this if homebrew is installed, aka on macs
if [ -d "/opt/homebrew/bin/brew" ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# rust
. "$HOME/.cargo/env"

path=(
  $HOME/.local/bin
  $HOME/bin
  $path
)
export PATH

export EDITOR="nvim"
