# zsh does not look into ~/.config, so you need to make a symlink:
# ln -s ~/.config/zsh/zshrc ~/.zshrc

# Forgot some Oh My Zsh settings? See the .zshrc template file that came
# with the installation at:
# https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template

# ==================================================================================================

# A wrapper for prepending to the $PATH variable.
# Note that adding entries to $PATH via this function works like a stack:
# later arguments get searched first.
#
# Usage:
#   add_to_path dir1 dir2 [...]
#                    ^^^^ this will get searched before dir1, but after other arguments
add_to_path() {
  for dir in "$@"
  do
    if ! [[ "$PATH" =~ "$dir:" ]]; then
      PATH="$dir:$PATH"
    fi
  done
  export PATH
}
# Configures user specific environment.
add_to_path \
  "$HOME/bin" \
  "$HOME/.local/bin" \

# Path to Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Sets the theme for Oh My Zsh.
ZSH_THEME="agnoster"

# Oh My Zsh plugins.
plugins=(
  git
  fzf-tab
)

# Loads Oh My Zsh.
source $ZSH/oh-my-zsh.sh

# ===== User configuration =====

# Rust installation.
. "$HOME/.cargo/env"

# Sets the default command-line editor to be neovim.
export EDITOR='nvim'

# Outputs a human readable output of env variables when
# there are multiple entries. Is otherwise the same as `echo`
# when there is only one entry.
#
# Usage:
#   echoenv $VARIABLE
echoenv() {
  tr ':' '\n' <<<$1
}

# Outputs the list of all installed rpm packages to ~/rpm_qa.txt, overwriting if it exists.
alias rpm-qa="rpm -qa > rpm_qa.txt"

# Activates the base conda environment.
alias do-conda-activate="~/miniconda3/bin/conda shell.bash hook"
alias conda-activate="eval $(do-conda-activate)"

# Opens the Alacritty config.
alias alacritty-config="nvim $HOME/.config/alacritty/alacritty.toml"

# Opens the tmux config.
alias tmux-config="nvim $HOME/.config/tmux/tmux.conf"

# Opens this file.
# Note that we open the link instead of the actual file.
alias zshrc="nvim $HOME/.zshrc"

# Alias for git to handle config files version tracking.
alias config="/usr/bin/git --git-dir=$HOME/.config/.cfg/ --work-tree=$HOME/.config"
