# NOTE: oh-my-zsh default template and docs for options:
# https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template

# these lines by the zsh "init utility" should be kept at the top
# {{{ zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# }}}
# {{{ compinstall
zstyle :compinstall filename '/home/felix/.zshrc'

autoload -Uz compinit
compinit
# }}}

# {{{ $PATH
# A wrapper for prepending to the $PATH variable.
# Note that adding entries to $PATH via this function works like a stack:
# later arguments get searched first.
#
# Usage:
#   add_to_path dir1 dir2 [...]
#                    ^^^^ this will get searched before dir1, but after other arguments
add_to_path() {
  for dir in "$@"
  do
    if ! [[ "$PATH" =~ "$dir:" ]]; then
      PATH="$dir:$PATH"
    fi
  done
  export PATH
}
add_to_path \
  "$HOME/bin" \
  "$HOME/.local/bin" \
# }}}

# {{{ oh-my-zsh setup
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

plugins=(
  git
  fzf-tab
)

source $ZSH/oh-my-zsh.sh
# }}}

# Rust installation.
. "$HOME/.cargo/env"

export EDITOR='nvim'

# {{{ aliases
# Outputs a human readable output of env variables when
# there are multiple entries. Is otherwise the same as `echo`
# when there is only one entry.
#
# Usage:
#   echoenv $VARIABLE
echoenv() {
  tr ':' '\n' <<<$1
}

alias rpm-qa="rpm -qa > rpm_qa.txt"

alias do-conda-init="~/miniconda3/bin/conda shell.bash hook"
alias conda-init="eval $(do-conda-init)"

alias alacritty-config="nvim $HOME/.config/alacritty/alacritty.toml"

alias tmux-config="nvim $HOME/.config/tmux/tmux.conf"

# Note that we open the link instead of the actual file.
alias zshrc="nvim $HOME/.zshrc"

alias config="/usr/bin/git --git-dir=$HOME/.config/.cfg/ --work-tree=$HOME/.config"
# }}}

# vim: foldmethod=marker foldlevel=0
