# these lines by the zsh "init utility" should be kept at the top
# {{{ zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -v
# }}}
# {{{ compinstall
zstyle :compinstall filename "$HOME/.zshrc"

autoload -Uz compinit
compinit
# }}}

# NOTE: oh-my-zsh default template and docs for options:
# https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template

# {{{ oh-my-zsh setup
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

plugins=(
  git
  fzf-tab
)

source $ZSH/oh-my-zsh.sh
# }}}

# {{{ aliases
# Outputs a human readable output of env variables when
# there are multiple entries. Is otherwise the same as `echo`
# when there is only one entry.
#
# Usage:
#   echoenv $VARIABLE
echoenv() {
  tr ":" "\n" <<<$1
}

alias rpm-qa="rpm -qa > rpm_qa.txt"

alias editrc="nvim ~/.rc/"
# Note that we open the links instead of the actual file.
alias alacrittyrc="nvim $HOME/.config/alacritty/alacritty.toml"
alias nvimrc="nvim $HOME/.config/nvim/init.lua"
alias tmuxrc="nvim $HOME/.config/tmux/tmux.conf"
alias zshrc="nvim $HOME/.zshrc"
# }}}

# vim: foldmethod=marker foldlevel=0
